var animalFacts = [
'Seeotter halten beim Schlafen oft Händchen, damit sie nicht auseinander treiben.',
'Oktopusse haben drei Herzen und blaues Blut.',
'Kühe bilden enge Freundschaften und sind gestresst, wenn sie getrennt werden.',
'Schmetterlinge schmecken mit ihren Füßen.',
'Eisbären haben schwarze Haut unter ihrem weißen Fell.',
'Eichhörnchen pflanzen versehentlich Millionen Bäume, weil sie vergrabene Nüsse vergessen.',
'Kängurus können nicht rückwärts hüpfen.',
'Flamingos werden grau geboren und bekommen ihre rosa Farbe durch Nahrung.',
'Wombat-Kot ist würfelförmig, damit er nicht wegrollt.',
'Kolibris sind die einzigen Vögel, die rückwärts fliegen können.',
'Seepferdchen bleiben ein Leben lang zusammen und die Männchen tragen die Babys aus.',
'Bienen teilen ihren Artgenossen mit einem Tanz die Richtung zu Futterquellen mit.',
'Elefanten können nicht springen.',
'Faultiere verdauen eine Mahlzeit manchmal fast einen Monat lang.',
'Delfine geben sich individuelle Namen in Form von charakteristischen Pfiffen.',
'Haie gibt es schon länger auf der Erde als Bäume.',
'Katzen verbrauchen rund 70 % ihres Lebens mit Schlafen.',
'Ameisen schlafen nie im klassischen Sinn, sondern machen hunderte Minutenschläfchen.',
'Garnelen haben ihr Herz im Kopf.',
'Blutegel haben 32 Gehirne.',
'Koalas haben Fingerabdrücke, die menschlichen erstaunlich ähnlich sind.',
'Pinguine machen ihrem Partner manchmal einen Antrag mit einem besonders schönen Stein.',
'Schnecken können je nach Art mehrere Jahre schlafen.',
'Hunde haben einen Nase-Abdruck, der so einzigartig ist wie ein menschlicher Fingerabdruck.',
'Pottwale schlafen aufrecht stehend im Wasser.',
'Krähen können sich menschliche Gesichter merken und schlechte Erfahrungen weitererzählen.',
'Gorillas können sich beim Menschen mit Schnupfen anstecken.',
'Hummeln können auch bei Temperaturen fliegen, die für andere Insekten zu kalt sind.',
'Viele Schildkröten können durch ihren Hintern atmen.',
'Flusspferde schwitzen eine rote Flüssigkeit aus, die als Sonnenschutz dient.',
'Giraffen haben wie Menschen sieben Halswirbel, nur sind sie deutlich länger.',
'Marienkäfer beißen manchmal, wenn sie nach Salzen oder Wasser suchen.',
'Quallen bestehen zu etwa 95 % aus Wasser und haben kein Gehirn.',
'Geparde können nicht brüllen, sie miauen und schnurren wie Hauskatzen.',
'Pudel wurden ursprünglich als Jagdhunde für die Wasserjagd gezüchtet.',
'Pandas markieren ihr Revier manchmal im Handstand.',
'Strauße haben Augen, die größer sind als ihr Gehirn.',
'Biber haben orangefarbene Zähne, weil sie Eisen enthalten.',
'Schweine träumen genau wie Menschen beim Schlafen.',
'Taranteln halten sich manchmal kleine Frösche als „Haustiere“, um Schädlinge vom Nest fernzuhalten.',
'Piranhas sind meist Aasfresser und greifen lebende Menschen fast nie an.',
'Lamas spucken nicht grundlos, sondern meist zur Klärung von Rangordnungen.',
'Eulen können ihre Augen nicht bewegen, dafür aber den Kopf um 270 Grad drehen.',
'Grillen hören mit ihren Vorderbeinen.',
'Clownfische können ihr Geschlecht wechseln, wenn das dominante Weibchen stirbt.',
'Mücken werden besonders von Menschen angezogen, die gerade Bananen gegessen haben.',
'Seekühe pupsen, um ihre Auftriebskraft im Wasser zu regulieren.',
'Chinchillas baden nicht in Wasser, sondern in feinem Vulkan-Sand.',
'Gänse trauern monatelang, wenn sie ihren Partner verlieren.',
'Axolotl können Teile ihres Herzens, Gehirns und ihrer Gliedmaßen nachbilden.',
'Mistkäfer orientieren sich nachts an der Milchstraße.',
'Regenwürmer haben fünf Herzpaare.',
'Ziegen haben rechteckige Pupillen, die ihnen ein besonders weites Sichtfeld geben.',
'Eichhörnchen erkennen sich gegenseitig oft am Geruch.',
'Kakerlaken können ohne Kopf noch mehrere Wochen überleben.',
'Kaimane nutzen Stöcke auf dem Kopf als Köder für Vögel während der Nistzeit.',
'Glühwürmchen leuchten durch eine chemische Reaktion nahezu ohne Wärmeverlust.',
'Känguru-Babys sind bei der Geburt nur so groß wie eine Bohne.',
'Tauben können komplexe mathematische Muster und Kunststile unterscheiden.',
'Narwale nutzen ihren Stoßzahn vor allem als Sinnesorgan für Wassertemperatur und Salzgehalt.',
'Waschbären „waschen“ ihr Essen nicht aus Hygiene, sondern um ihren Tastsinn im Wasser zu schärfen.',
'Auf dem Fell von Faultieren wächst ein eigenes Ökosystem aus Algen.',
'Opossums stellen sich bei Gefahr tot und verströmen dabei Verwesungsgeruch.',
'Termiten bauen Klimaanlagen in ihre Bauten ein, die die Temperatur konstant halten.',
'Ratten lachen im Ultraschallbereich, wenn man sie kitzelt.',
'Knallkrebse schlagen so schnell zu, dass kurzzeitig Hitze wie auf der Sonnenoberfläche entsteht.',
'Esel haben hervorragende Gedächtnisleistungen und wiedererkennen Orte nach 25 Jahren.',
'Spechte wickeln ihre lange Zunge um den Schädel, um das Gehirn beim Hämmern zu schützen.',
'Buntbarsche erkennen sich gegenseitig an individuellen Gesichtern.',
'Schafe können sich bis zu 50 verschiedene Gesichter jahrelang merken.',
'Blauwale erzeugen die lautesten Geräusche im Tierreich.',
'Kolibris haben ein extrem schnelles Herz mit bis zu 1.200 Schlägen pro Minute.',
'Erdmännchen bilden Wachen aus, die laut rufen, sobald Gefahr droht.',
'Bienenkolonien entscheiden über Abstimmungen durch Vibrationen über den nächsten Nistplatz.',
'Albatrosse können jahrelang auf See bleiben, ohne an Land zu landen.',
'Pfeilgiftfrösche verlieren in Gefangenschaft ihre Giftigkeit, da sie das Gift aus der Wildnahrung bilden.',
'Zitteraale sind keine echten Aale, sondern verwandter mit Messerfischen.',
'Singvögel lernen ihre Lieder ähnlich wie menschliche Babys das Sprechen lernen.',
'Schildkröten existieren seit mehr als 220 Millionen Jahren.',
'Oktopusse nutzen manchmal Werkzeuge wie Kokosnussschalen als Schutzraum.',
'Mausohrfledermäuse orientieren sich nachts mit bis zu 200 Ultraschall-Rufen pro Sekunde.',
'Kakadus können im Takt der Musik tanzen und Rhythmen verstehen.',
'Stinktiere warnen Feinde zuerst mit einem Handstand, bevor sie sprühen.',
'Rentier-Augen wechseln im Winter ihre Farbe von Gold zu Blau.',
'Schnabeltiere schwitzen Milch aus ihrer Haut, da sie keine Zitzen haben.',
'Katzen können mehr als hundert verschiedene Laute erzeugen.',
'Insekten machen über 80 % aller bekannten Tierarten auf der Erde aus.',
'Eisvögel tauchen mit bis zu 40 km/h ins Wasser, um Fische zu fangen.',
'Bären stoßen während des Winterschlafs monatelang keinen Kot ab.',
'Hunde riechen rund 10.000 bis 100.000 Mal besser als Menschen.',
'Geparden nutzen ihren langen Schwanz wie ein Schiffsruder für scharfe Kurven.',
'Delfine schlafen mit nur einer Gehirnhälfte, während das andere Auge offen bleibt.',
'Wölfe können sich gegenseitig an der Stimme erkennen, auch wenn sie weit entfernt sind.',
'Papageien benennen ihre Küken mit individuellen Rufen.',
'Tintenfische können ihre Hautfarbe und -struktur in weniger als einer Sekunde anpassen.',
'Grashüpfer haben ihre Ohren am Bauch sitzend.',
'Libellen haben eine Jagderfolgsquote von rund 95 Prozent.',
'Elefanten können mit ihren Füßen tiefe Schwingungen im Boden wahrnehmen.',
'Kugelfische bauen kunstvolle Sandkreise, um Partner zu beeindrucken.',
'Nacktmulle spüren kaum Schmerz und erkranken so gut wie nie an Krebs.'
];

var factIndex = -1;
function showRandomFact() {
  var next = Math.floor(Math.random() * animalFacts.length);
  if (animalFacts.length > 1 && next === factIndex) next = (next + 1) % animalFacts.length;
  factIndex = next;
  document.getElementById('fact-text').textContent = animalFacts[next];
}
